Fix bazel.msan bazel-build-options argument (#17279)
Update usage of `"-c dbg"` in array to be `"-c" "dbg"` to prevent it from being
interpreted as a single argument with a space. This makes the usage consistent
with other usages in this file.

The existing format has been observed to cause issues:
```
ERROR: -c dbg :: Invalid options syntax: -c dbg
```

Signed-off-by: John Murray <murray@stripe.com>